### ISSUE TITLE
Review type cache invalidation

### ISSUE THREAD

**Issue by rochoa** [CartoDB/node-cartodb-psql#10]
Type cache stores `oid => name` relations per db name but it never expires them. When a given oid change for a name, for instance when upgrading an extension, the cache won't pickup that change.

We should have an eviction/expiration policy for that cache: for instance removing items when last connection for a database in closed so next time it will pickup again the `oid => name` relations.

cc @luisbosque

**Comment by Algunenano** [comment]
More or less fixed with https://github.com/CartoDB/node-cartodb-psql/pull/39
