### ISSUE TITLE
Type cache too eager

### ISSUE THREAD

**Issue by javitonino** [CartoDB/node-cartodb-psql#38]
When migrating a user from one database server to another, the type ids can change. The mapping from id -> name is cached in node memory, and it won't be refreshed until the server is restarted:

https://github.com/CartoDB/node-cartodb-psql/blob/master/lib/psql.js#L10
https://github.com/CartoDB/node-cartodb-psql/blob/master/lib/psql.js#L166-L190

So, when moving the user from one server to another, we will have incorrect type mappings until we restart SQL API. This causes problems like this https://github.com/CartoDB/support/issues/1863

A solution would be to tie the cache to the host ip as well as the database name, something that rochoa seems to have predicted in a comment 5 years old :crystal_ball:  https://github.com/CartoDB/node-cartodb-psql/blob/master/lib/psql.js#L163

cc @CartoDB/rt-managers

**Comment by javitonino** [comment]
Almost a dupe of https://github.com/CartoDB/node-cartodb-psql/issues/10

**Comment by rafatower** [comment]
reopening until updating the deps for the tiler as well... (thanks tonino for bringing this to my attention)

**Comment by rafatower** [comment]
Out of curiosity:
https://www.npmjs.com/package/cartodb-psql?activeTab=dependents
```
    @dinomap/map-core
    windshaft
    camshaft
```

**Comment by rafatower** [comment]
Deployed to the tiler as well, closing this. Hope next migrations do not suffer from this
